name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build
      run: npm run build

    # Lint step removed

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DENTAL_DEPLOY_KEY }}
          known_hosts: '134.209.121.112'

      - name: Add server to known_hosts
        run: ssh-keyscan -H 134.209.121.112 >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean
        env:
          REACT_APP_API_URL: "http://10.116.0.2:5000"
        run: |
          ssh root@134.209.121.112 << 'EOF'
            set -e
            if [ ! -d /root/dental-frontend ]; then
              git clone https://github.com/tapiwago/dental.git /root/dental-frontend
            else
              cd /root/dental-frontend && git pull origin main
            fi
            cd /root/dental-frontend
            echo "VITE_API_BASE_URL=/api" > .env.production
            echo "NODE_ENV=production" >> .env.production
            npm install --legacy-peer-deps
            npm run build
            apt-get update -qq
            apt-get install -y nginx
            rm -rf /var/www/html/*
            cp -r dist/* /var/www/html/
            cat > /etc/nginx/sites-available/dental-frontend << 'NGINXEOF'
          server {
              listen 80;
              server_name _;
              root /var/www/html;
              index index.html;
              location / {
                  try_files $uri $uri/ /index.html;
              }
              location /api/ {
                  proxy_pass http://localhost:5000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_cache_bypass $http_upgrade;
              }
          }
          NGINXEOF
            ln -sf /etc/nginx/sites-available/dental-frontend /etc/nginx/sites-enabled/
            rm -f /etc/nginx/sites-enabled/default
            nginx -t && systemctl reload nginx
            systemctl enable nginx
            echo "🚀 Deployment completed successfully!"
            echo "Live site URL: http://134.209.121.112"
          EOF
